.TH CONVERTALL "1" "August 2013" "convertall Usage:" "User Commands"
.SH NAME
convertall \- A very flexible unit converter
.SH DESCRIPTION
Usage:
.IP
convertall [qt\-options]
.SS "-or- (non-GUI):"
.IP
convertall [options] [number] from_unit [to_unit]
.SS "-or- (non-GUI):"
.IP
convertall \fB\-i\fR [options]
.PP
Units with spaces must be "quoted"
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-decimals\fR=\fInum\fR
set number of decimals to show
.TP
\fB\-f\fR, \fB\-\-fixed\-decimals\fR
show set number of decimals, even if zeros
.TP
\fB\-h\fR, \fB\-\-help\fR
display this message and exit
.TP
\fB\-i\fR, \fB\-\-interactive\fR
interactive command line mode (non\-GUI)
.TP
\fB\-q\fR, \fB\-\-quiet\fR
convert without further prompts
.TP
\fB\-s\fR, \fB\-\-sci\-notation\fR
show results in scientific notation
.IP
convertall [qt\-options]
.SS "-or- (non-GUI):"
.IP
convertall [options] [number] from_unit [to_unit]
.SS "-or- (non-GUI):"
.IP
convertall \fB\-i\fR [options]
.PP
Units with spaces must be "quoted"
.TP
\fB\-d\fR, \fB\-\-decimals\fR=\fInum\fR
set number of decimals to show
.TP
\fB\-f\fR, \fB\-\-fixed\-decimals\fR
show set number of decimals, even if zeros
.TP
\fB\-h\fR, \fB\-\-help\fR
display this message and exit
.TP
\fB\-i\fR, \fB\-\-interactive\fR
interactive command line mode (non\-GUI)
.TP
\fB\-q\fR, \fB\-\-quiet\fR
convert without further prompts
.TP
\fB\-s\fR, \fB\-\-sci\-notation\fR
show results in scientific notation
.SH "SEE ALSO"
The full documentation for
.B convertall
is maintained as a Texinfo manual.  If the
.B info
and
.B convertall
programs are properly installed at your site, the command
.IP
.B info convertall
.PP
should give you access to the complete manual.